server:
  port: 8181

logging:
  level:
    org.apache.kafka.clients: INFO


spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: root_cm
    password: root_cm
    driver-class-name: org.postgresql.Driver




#  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true


